plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'TwootrServer'
}

group = 'br.com.drianodev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
    implementation 'org.java-websocket:Java-WebSocket:1.5.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'org.hsqldb:hsqldb:2.7.2'
    implementation 'org.eclipse.jetty:jetty-server:9.4.53.v20231009'
    implementation 'org.eclipse.jetty:jetty-servlet:9.4.53.v20231009'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.5.0'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}